# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    first-job:
      runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world"
        
      - name: Print Goodbye
        run: echo "Done-Bye!!" 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
