name: MUlti-job Workflow
on: [push]
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in job one
        run: echo "Job one completed"
  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in job two
        run: echo "Job two start after Job one"
