name: Workflows Commands

# Controls when the workflow will run
on: [push]
jobs:
  testing-workflow-commands:
    runs-on: ubuntu-latest
    steps:
      -name: Mask a Sensitive value
       run: |
         echo "::add-mask::Mysecret123"
         echo "Mask value added"
      -name: Echo masked value
       run: |
         echo "Mysecret123"
         
