name: Workflow Commands Demo
on: [push]
jobs:
  demo-workflow-commands:
    runs-on: ubuntu-latest
    steps:
      # Masking sensitive values
      - name: Mask a Sensitive Value
        run: |
          echo "::add-mask::MySecret123"
          echo "Masked value added"

      - name: Echo Masked Value
        run: |
          echo "MySecret123"
